dbfilename redis_queue.rdb
dir /Users/thaidoantuan/workspace/frappe-dev/bench/config/pids
pidfile /Users/thaidoantuan/workspace/frappe-dev/bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /Users/thaidoantuan/workspace/frappe-dev/bench/config/redis_queue.acl
